=== Acidburn0zzz/OpenStudio/openstudiocore/resources/standardsinterface/DataDictionary/DataDictionary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 (http://www.altova.com) by Elaine Hale (National Renewable Energy Laboratory) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DataDictionary">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Universal" minOccurs="0">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="Term" type="Term"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="CEC" minOccurs="0">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="Term" type="Term"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Term">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="definition" type="xs:string"/>
			<xs:element name="type">
				<xs:complexType>
					<xs:choice>
						<xs:element name="boolean">
							<xs:complexType/>
						</xs:element>
						<xs:element name="integer">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="min" type="xs:int" minOccurs="0"/>
									<xs:element name="max" type="xs:int" minOccurs="0"/>
									<xs:element name="units" type="xs:string" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="double">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="min" type="xs:double" minOccurs="0"/>
									<xs:element name="max" type="xs:double" minOccurs="0"/>
									<xs:element name="units" type="xs:string" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="enumeration">
							<xs:complexType>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="value" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="noun">
							<xs:complexType/>
						</xs:element>
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="relationships" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Relationships present in controlled vocabularies and thesauries.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="isa" minOccurs="0">
							<xs:complexType>
								<xs:sequence maxOccurs="unbounded">
									<xs:element name="name" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="broaderThan" minOccurs="0">
							<xs:complexType>
								<xs:sequence maxOccurs="unbounded">
									<xs:element name="name" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="narrowerThan" minOccurs="0">
							<xs:complexType>
								<xs:sequence maxOccurs="unbounded">
									<xs:element name="name" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="synonyms" minOccurs="0">
							<xs:complexType>
								<xs:sequence maxOccurs="unbounded">
									<xs:element name="name" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="antonyms" minOccurs="0">
							<xs:complexType>
								<xs:sequence maxOccurs="unbounded">
									<xs:element name="name" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Acidburn0zzz/OpenStudio/openstudiocore/resources/standardsinterface/DataDictionary/DataDictionary.xml
<?xml version="1.0" encoding="UTF-8"?>
<DataDictionary xsi:noNamespaceSchemaLocation="DataDictionary.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Universal>
    <Term>
      <name>Attic</name>
      <definition>JA2: Attic is an enclosed unconditioned space directly below the roof and above the ceiling.
 
JA 4 has separate tables for assigning UFactor to roofs with attics:  Table 4.2.1  U-factors of Wood Framed Attic Roofs and Table 4.2.4  U-factors of Metal Framed Attic Roofs.</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Building Story</name>
      <definition>T24:  No definition, but the number of stories is used to differentiate between low rise residential and high rise residential which uses the nonresidential standards for the most part
 
In Section 131  Indoor Lighting Controls That Shall Be Installed (d) Shut-off Controls:  there is a rule that every story shall have a lighting control shut off all the lights</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Ceiling</name>
      <definition>JA1:  Ceiling is the interior upper surface of a space separating it from an attic, plenum, indirectly or directly conditioned space or the roof assembly, which has a slope less than 60 degrees from horizontal.</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Construction Assembly</name>
      <definition>Joint Appendix 4 contains tables of Construction Assemblies for roof, ceiling, wall and floor and their associated U Factors and other thermal properties, used in performance compliance.
 
In Section 143 of Title 24 Part 6 construction assemblies are greatly simplified for assignment of prescriptive U Factors.</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Crawl Space</name>
      <definition>T24: Crawl Space is a space immediately under the first floor of a building adjacent to grade.
 
In JA IV there are tables for floors with and withour crawl spaces e.g. Table 4.4.1  Standard U-factors for Wood-Framed Floors with a Crawl Space Floor and Table 4.4.2  Standard U-factors for Wood Framed Floors without a Crawl Space</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Envelope</name>
      <definition>T24: Building Envelope is the ensemble of exterior and demising partitions of a building that enclose conditioned space.
 
NR ACM: 2.3.1.3 Enclosed Unconditioned  ... Compliance software shall require the user to identify the space as unconditioned and to enter all applicable envelope information, in a similar manner to a conditioned space.</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Exterior Door</name>
      <definition>Title 24 Part 6 definition:
Door is an operable opening in the building envelope that is not a fenestration product, including swinging and roll-up doors, fire doors, and access hatches. Doors that are more than one-half glass in area are considered a fenestration product.
 
Exterior Door is an operable door through an exterior partition that is opaque or has a glazed area that is less than or equal to one-half of the door area.</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Exterior Surface Properties</name>
      <definition>The thermal properties of exterior surfaces such as solar reflectance and emissivity is mainly evaluated for roofing surfaces e.g. Section 118  Mandatory Requirements For Insulation And Roofing Products (i) Roofing Products Solar Reflectance and Thermal Emittance.  There is no mention of exterior surface roughness in any of the Standards documents</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Fenestration</name>
      <definition>T24: FENESTRATION PRODUCT is any transparent or translucent material plus any sash, frame, mullions and dividers, in the envelope of a building, including, but not limited to, windows, sliding glass doors, French doors, skylights, curtain walls, garden windows, and other doors with a glazed area of more than one half of the door area.</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Fenestration Construction</name>
      <definition>T24: Fenestration construction is defined in the Fenestration Product which is any transparent or translucent material plus any sash, frame, mullions and dividers, that fills an open space  in the envelope of a building, such as a window, sliding glass door, French door, skylight, curtain wall, garden window, or an open space in a door where the opening is more  than one half of the door area.</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Fenestration Construction Skylight</name>
      <definition>The same attributes of the skylight construction appear in text and tables but there is no formal definition. </definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Fenestration Construction Vertical</name>
      <definition>The same attributes of the vertical construction which is usually termed Window appear in text and tables but there is no formal definition.</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Fenestration Skylight</name>
      <definition>From the glossary:
 
SKYLIGHT is fenestration installed on a roof less than 60 degrees from the horizontal</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Fenestration Vertical</name>
      <definition>Glossary definitions below make it clear that all vertical fenestration is referred to as a Window
 
FENESTRATION PRODUCT is any transparent or translucent material plus any sash, frame, mullions and dividers, in
the envelope of a building, including, but not limited to, windows, sliding glass doors, French doors, skylights, curtain
walls, garden windows, and other doors with a glazed area of more than one half of the door area.
 
 
WINDOW is fenestration that is not a skylight
 </definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Floor</name>
      <definition>T24: Floor/Soffit: is a horizontal exterior partition, or a horizontal demising partition, under conditioned space. For low-rise residential occupancies, exterior floors also include those on grade.
 
NOTE:  It was decided by CEC staff reviewers that soffit should be dropped from the term.</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Floors</name>
      <definition>The Standards use the sum the floor area for all the Building Stories in the Building for different purposes, including prescribing when to apply residential and nonresidential standards.  </definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Insulation</name>
      <definition>T24: Insulation is part of the Construction Assemblies defined in Joint Appendix 4 tables which define insulation type, placement, thickness, number of layers, and R values.</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Layers</name>
      <definition>The Standards Joint Appendix 4 presents whole construction assemblies which do separate out the insulation layers, and provides some information on values for air layers and</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Material</name>
      <definition>The Standards currently do not use a layer by layer approach to construction assemblies although JA 4 does describe underlying layer calculations used in the construction assembly tables that assign values for U-Factor and other thermal measurements.</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Materials</name>
      <definition>JA 4 mainly contains tables of the defined roof, wall and floor construction assemblies.  It doesn't use a material layer approach, although there are explanations of how elements of a construction assembly contribute to the assigned values.   </definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Opening Geometry</name>
      <definition>The size of openings and their orientation is used in the Standards mainly in the assignment of Relative Solar Heat Gain values for windows   </definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Partition</name>
      <definition>T24 uses Partition in the same way as a base type for wall, floor, roof and ceiling.  There are definitions in Title 24 Section 101 for Demising Partitions and Exterior Partitions. 
 
 Demising Partition is a wall, fenestration, floor, or ceiling that separates conditioned space from enclosed unconditioned space.
 
Exterior Partition is an opaque, translucent, or transparent solid barrier that separates conditioned space from outdoors including the ground.</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Rectangular Surface Size</name>
      <definition>Surface area is used and evaluated throughout the Standards in order to apply different regulations, especially floor area, but also wall area, roof area and fenestration area.</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Roof</name>
      <definition>T24: Roof is the outside cover of a building or structure including the structural supports, decking, and top layer that is exposed to the outside with a slope less than 60 degrees from the horizontal.</definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Roof Section</name>
      <definition></definition>
      <type><noun/></type>
    </Term>
    <Term>
      <name>Room</name>
      <definition>There is no formal definition of Room, however the meaning implied in it's use for calculating room cavity ration,  is a space bound by physical ceiling high partitions on all sides.</definition>
